[workspace]
members = [
    "kernel", 
    "kernel_lib",
    "linker", 
    "xtask", 
    "easy-fs",
    "console",
    "allocator", 
    "context", 
    "syscall",
    "vm", 
    "signal-defs", "signal-impl", "signal",
    "task-manage", "sync",
    "user", "user_libs"
    ]
default-members = ["xtask"]

exclude = ["mod_mgmt", "easy-fs-fuse"]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"