[workspace]
members = [
    "kernel", 
    "tconfig",
    "memory",
    "sync",
    "task",
    "sbi",
    "drivers",
    "safe_cell",
    "asynchronous",
    "xtask", 
    "easy-fs", 
    "application/easy-fs-fuse",
    "application/user",
    ]
default-members = ["xtask"]

exclude = [
    "mod_mgmt",
    "other_libs/*",
    ]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"