[workspace]
members = [
    "application/easy-fs-fuse",
    "application/user",
    "application/ring_scheduler",
    "easy-fs", 
    "kernel", 
    "memory",
    "safe_cell",
    "tconfig",
    ]
default-members = ["kernel"]

exclude = [
    "mkConfig",
    "script",
    "other_libs/*",
    ]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
riscv = { git = "https://github.com/Andre-HJR/riscv.git", rev = "031d548a" }