[workspace]
members = [
    "kernel", 
    "linker", 
    "xtask", 
    "easy-fs", 
    "allocator", 
    "context", 
    "syscall",
    "vm", 
    "signal-defs", "signal-impl", "signal",
    "task-manage", "sync"
    ]
default-members = ["xtask"]

exclude = ["mod_mgmt"]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"