[workspace]
members = [
    "kernel", 
    "tconfig",
    "drivers",
    "xtask", 
    "application/easy-fs", "application/easy-fs-fuse",
    "application/user",
    ]
default-members = ["xtask"]

exclude = [
    "mod_mgmt",
    "other_libs/*",
    "easy-fs",
    "easy-fs-fuse",
    "user"
    ]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"