[workspace]
members = [
    "application/easy-fs-fuse",
    "application/user",
    "asynchronous",
    "drivers",
    "easy-fs", 
    "fs",
    "kernel", 
    "memory",
    # mod_mgmt
    "safe_cell",
    "sbi",
    "sync",
    "syscall",
    "task",
    "tconfig",
    "timer",
    "tlib",
    "trap",
    "xtask", 
    ]
default-members = ["xtask"]

exclude = [
    "mkConfig",
    "mod_mgmt",
    "script",
    "other_libs/*",
    ]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"