[workspace]
members = [
    "kernel", 
    "xtask", 
    "easy-fs", "easy-fs-fuse",
    "user",
    ]
default-members = ["xtask"]

exclude = [
    "mod_mgmt",
    "kernel_lib",
    "linker", 
    "console",
    "allocator", 
    "context", 
    "syscall",
    "signal-defs", "signal-impl", "signal",
    "task-manage", "sync",
    "vm", "user_libs",
    ]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"