[package]
name = "user_libs"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
rcore-console = { path = "../console", package="console"}
syscall = { path = "../syscall", features = ["user"] }
customizable-buddy = "0.0.2"
