#! /usr/bin/perl -w


package UtilsCargo;

my $_cmd = "cargo";
my $_target = "--target=\"riscv64gc-unknown-none-elf\"";

sub cargo_clean {

}

sub cargo_new {

}

# cargo check in Workspace
sub cargo_check {
    @argList = @_;
    $_type = "check";
    $_crate = $argList[0];
    $_target_require = $argList[1];
    print (($_target_require eq "true") ? 
    "\e[31m". $_cmd . " " . $_type . " -p ". $_crate . " ". $_target . "\e[0m\n":
    "\e[31m". $_cmd . " " . $_type . " -p ". $_crate . "\e[0m\n");
    system (($_target_require eq "true") ? 
    $_cmd . " " . $_type . " -p ". $_crate . " ". $_target :
    $_cmd . " " . $_type . " -p ". $_crate );

}

sub cargo_build {

}

package main;

@commander = @ARGV;

sub check {
    my $crate = $ARGV[1] ? $ARGV[1] : "";
    my $target_require = $ARGV[2] ? $ARGV[2] : true;
    &UtilsCargo::cargo_check($crate, $target_require);
}

$commander[0]();