#! /usr/bin/perl -w


package UtilsClean;


sub cargo_clean {
    system "cargo clean";
}

sub build_clean {
    system "rm -rf build";
}


package main;

@commander = @ARGV;

sub clean {
    &UtilsClean::cargo_clean();
    &UtilsClean::build_clean();
}

$commander[0]();